#pragma once
#define num_syntax_terminal 21
#define num_syntax_nonterminal 15
#define num_dfa_state 85
#define TERMINAL_MAX_LENGTH 100

#define EMPTY 100

//ACTION 배열
char ACTION[num_syntax_terminal + 10][TERMINAL_MAX_LENGTH] = {
{'v','t','y','p','e'},
{'n','u','m',},
{'f','l','o','a','t'},
{'l','i','t','e','r','a','l'},
{'i','d'},
{'i','f'},
{'e','l','s','e'},
{'w','h','i','l','e'},
{'f','o','r'},
{'r','e','t','u','r','n'},
{'a','d','d','s','u','b'},
{'m','u','l','t','d','i','v'},
{'a','s','s','i','g','n'},
{'c','o','m','p'},
{'s','e','m','i'},
{'c','o','m','m','a'},
{'l','p','a','r','e','n'},
{'r','p','a','r','e','n'},
{'l','b','r','a','c','e'},
{'r','b','r','a','c','e'},
{'$'}
};


int ACTION_length[num_syntax_terminal + 10] = {5,3,5,7,2,2,4,5,3,6,6,7,6,4,4,5,6,6,6,6,1};

int SLR_table_ACTION[num_dfa_state + 10][num_syntax_terminal + 10] = {
//vtype,num,	float,literal,	id,		if,		else,while,		for,return,		addsub,multdiv, assign,comp,	semi,comma,		lparen,rparen,	lbrace,rbrace,	$
{	4,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   -3},//T0
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	    0},//T1
{	4,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   -3},//T2
{	4,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   -3},//T3
{EMPTY,EMPTY,	EMPTY,EMPTY,	    7,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY},//T4
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   -1},//T5
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   -2},//T6
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   10,EMPTY,	    9,EMPTY,	   11,EMPTY,	EMPTY,EMPTY,	EMPTY},//T7
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   12,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY},//T8
{   -4,EMPTY,	EMPTY,EMPTY,	   -4,   -4,	EMPTY,   -4,	   -4,   -4,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,   -4,	   -4},//T9
{EMPTY,   20,	   21,   14,	   19,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   18,EMPTY,	EMPTY,EMPTY,	EMPTY},//T10
{   23,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,   -9,	EMPTY,EMPTY,	EMPTY},//T11
{   -5,EMPTY,	EMPTY,EMPTY,	   -5,   -5,	EMPTY,   -5,	   -5,   -5,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,   -5,	   -5},//T12
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   -6,EMPTY,	EMPTY,   -6,	EMPTY,EMPTY,	EMPTY},//T13
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	  -22,EMPTY,	EMPTY,  -22,	EMPTY,EMPTY,	EMPTY},//T14
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	  -21,EMPTY,	EMPTY,  -21,	EMPTY,EMPTY,	EMPTY},//T15
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   24,EMPTY,	EMPTY,EMPTY,	  -24,EMPTY,	EMPTY,  -24,	EMPTY,EMPTY,	EMPTY},//T16
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	  -26,   25,	EMPTY,EMPTY,	  -26,EMPTY,	EMPTY,  -26,	EMPTY,EMPTY,	EMPTY},//T17
{EMPTY,   20,	   21,EMPTY,	   19,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   18,EMPTY,	EMPTY,EMPTY,	EMPTY},//T18
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	  -28,  -28,	EMPTY,  -28,	  -28,EMPTY,	EMPTY,  -28,	EMPTY,EMPTY,	EMPTY},//T19
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	  -29,  -29,	EMPTY,  -29,	  -29,EMPTY,	EMPTY,  -29,	EMPTY,EMPTY,	EMPTY},//T20
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	  -30,  -30,	EMPTY,  -30,	  -30,EMPTY,	EMPTY,  -30,	EMPTY,EMPTY,	EMPTY},//T21
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,   27,	EMPTY,EMPTY,	EMPTY},//T22
{EMPTY,EMPTY,	EMPTY,EMPTY,	   28,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY},//T23
{EMPTY,   20,	   21,EMPTY,	   19,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   18,EMPTY,	EMPTY,EMPTY,	EMPTY},//T24
{EMPTY,   20,	   21,EMPTY,	   19,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   18,EMPTY,	EMPTY,EMPTY,	EMPTY},//T25
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,   31,	EMPTY,EMPTY,	EMPTY},//T26
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   32,EMPTY,	EMPTY},//T27
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,   34,	EMPTY,  -11,	EMPTY,EMPTY,	EMPTY},//T28
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	  -23,EMPTY,	EMPTY,  -23,	EMPTY,EMPTY,	EMPTY},//T29
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	  -25,EMPTY,	EMPTY,EMPTY,	  -25,EMPTY,	EMPTY,  -25,	EMPTY,EMPTY,	EMPTY},//T30
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	  -27,  -27,	EMPTY,  -27,	  -27,EMPTY,	EMPTY,  -27,	EMPTY,EMPTY,	EMPTY},//T31
{   42,EMPTY,	EMPTY,EMPTY,	   43,   37,	EMPTY,   38,	   39,  -13,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,  -13,	EMPTY},//T32
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,   -8,	EMPTY,EMPTY,	EMPTY},//T33
{   44,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY},//T34
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,   46,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY},//T35
{   42,EMPTY,	EMPTY,EMPTY,	   43,   37,	EMPTY,   38,	   39,  -13,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,  -13,	EMPTY},//T36
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   48,EMPTY,	EMPTY,EMPTY,	EMPTY},//T37
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   49,EMPTY,	EMPTY,EMPTY,	EMPTY},//T38
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   50,EMPTY,	EMPTY,EMPTY,	EMPTY},//T39
{  -14,EMPTY,	EMPTY,EMPTY,	  -14,  -14,	EMPTY,  -14,	  -14,  -14,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,  -14,	EMPTY},//T40
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   51,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY},//T41
{EMPTY,EMPTY,	EMPTY,EMPTY,	   52,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY},//T42
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   10,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY},//T43
{EMPTY,EMPTY,	EMPTY,EMPTY,	   53,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY},//T44
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,   54,	EMPTY},//T45
{EMPTY,   20,	   21,EMPTY,	   19,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   18,EMPTY,	EMPTY,EMPTY,	EMPTY},//T46
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,  -12,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,  -12,	EMPTY},//T47
{EMPTY,   20,	   21,EMPTY,	   19,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   18,EMPTY,	EMPTY,EMPTY,	EMPTY},//T48
{EMPTY,   20,	   21,EMPTY,	   19,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   18,EMPTY,	EMPTY,EMPTY,	EMPTY},//T49
{EMPTY,EMPTY,	EMPTY,EMPTY,	   43,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY},//T50
{  -15,EMPTY,	EMPTY,EMPTY,	  -15,  -15,	EMPTY,  -15,	  -15,  -15,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,  -15,	EMPTY},//T51
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   10,EMPTY,	    9,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY},//T52
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,   34,	EMPTY,  -11,	EMPTY,EMPTY,	EMPTY},//T53
{   -7,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	  -7},//T54
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   61,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY},//T55
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,   62,	EMPTY,EMPTY,	EMPTY},//T56
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,   63,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY},//T57
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,   64,	EMPTY,EMPTY,	EMPTY},//T58
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   65,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY},//T59
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,  -10,	EMPTY,EMPTY,	EMPTY},//T60
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,  -32,	EMPTY},//T61
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   66,EMPTY,	EMPTY},//T62
{EMPTY,   20,	   21,EMPTY,	   19,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   18,EMPTY,	EMPTY,EMPTY,	EMPTY},//T63
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   68,EMPTY,	EMPTY},//T64
{EMPTY,   20,	   21,EMPTY,	   19,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   18,EMPTY,	EMPTY,EMPTY,	EMPTY},//T65
{   42,EMPTY,	EMPTY,EMPTY,	   43,   37,	EMPTY,   38,	   39,  -13,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,  -13,	EMPTY},//T66
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	  -31,EMPTY,	EMPTY,  -31,	EMPTY,EMPTY,	EMPTY},//T67
{   42,EMPTY,	EMPTY,EMPTY,	   43,   37,	EMPTY,   38,	   39,  -13,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,  -13,	EMPTY},//T68
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   72,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY},//T69
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,   73,	EMPTY},//T70
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,   74,	EMPTY},//T71
{EMPTY,EMPTY,	EMPTY,EMPTY,	   43,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY},//T72
{  -20,EMPTY,	EMPTY,EMPTY,	  -20,  -20,	   77,  -20,	  -20,  -20,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,  -20,	EMPTY},//T73
{  -17,EMPTY,	EMPTY,EMPTY,	  -17,  -17,	EMPTY,  -17,	  -17,  -17,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,  -17,	EMPTY},//T74
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,   78,	EMPTY,EMPTY,	EMPTY},//T75
{  -16,EMPTY,	EMPTY,EMPTY,	  -16,  -16,	EMPTY,  -16,	  -16,  -16,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,  -16,	EMPTY},//T76
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   79,EMPTY,	EMPTY},//T77
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	   80,EMPTY,	EMPTY},//T78
{   42,EMPTY,	EMPTY,EMPTY,	   43,   37,	EMPTY,   38,	   39,  -13,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,  -13,	EMPTY},//T79
{   42,EMPTY,	EMPTY,EMPTY,	   43,   37,	EMPTY,   38,	   39,  -13,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,  -13,	EMPTY},//T80
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,   83,	EMPTY},//T81
{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,   84,	EMPTY},//T82
{  -19,EMPTY,	EMPTY,EMPTY,	  -19,  -19,	EMPTY,  -19,	  -19,  -19,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,  -19,	EMPTY},//T83
{  -18,EMPTY,	EMPTY,EMPTY,	  -18,  -18,	EMPTY,  -18,	  -18,  -18,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,  -18,	EMPTY},//T84

{EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY,EMPTY,	EMPTY},//T1
};

char* GOTO[num_syntax_nonterminal + 10] =
{ "CODE","VDECL","FDECL","ARG","MOREARGS","BLOCK","STMT","ASSIGN","RHS","EXPR","TERM","FACTOR","COND","RETURN","ELSE" };

int SLR_table_GOTO[num_dfa_state + 10][num_syntax_nonterminal + 10] = {
//CODE,VDECL,	 FDECL,  ARG,	MOREARGS,BLOCK,  STMT,ASSIGN,	 RHS,   EXPR,	TERM,FACTOR,	COND, RETURN,	ELSE
{    1,     2,	     3, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T0 
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T1
{    5,     2,	     3, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T2
{    6,     2,	     3, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T3
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY,     8,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T4
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T5
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T6
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T7
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T8
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T9
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	    13,    15,	   16,    17,	EMPTY, EMPTY,	EMPTY}, //T10
{EMPTY, EMPTY,	 EMPTY,    22,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T11
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T12
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T13
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T14
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T15
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T16
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T17
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY,    26,	   16,    17,	EMPTY, EMPTY,	EMPTY}, //T18
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T19
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T20
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T21
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T22
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T23
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY,    29,	   16,    17,	EMPTY, EMPTY,	EMPTY}, //T24
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	   30,    17,	EMPTY, EMPTY,	EMPTY}, //T25
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T26
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T27
{EMPTY, EMPTY,	 EMPTY, EMPTY,	   33, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T28
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T29
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T30
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T31
{EMPTY,    40,	 EMPTY, EMPTY,	EMPTY,    35,	   36,    41,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T32
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T33
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T34
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY,    45,	EMPTY}, //T35
{EMPTY,    40,	 EMPTY, EMPTY,	EMPTY,    47,	   36,    41,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T36
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T37
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T38
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T39
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T40
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T41
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY,     8,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T42
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T43
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T44
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T45
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY,    55,	EMPTY, EMPTY,	EMPTY}, //T46
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T47
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY,    57,	   56, EMPTY,	EMPTY}, //T48
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY,    57,	   58, EMPTY,	EMPTY}, //T49
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY,     59,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T50
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T51
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T52
{EMPTY, EMPTY,	 EMPTY, EMPTY,	   60, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T53
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T54
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T55
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T56
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T57
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T58
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T59
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T60
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T61
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T62
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY,    67,	EMPTY, EMPTY,	EMPTY}, //T63
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T64
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY,    57,	   69, EMPTY,	EMPTY}, //T65
{EMPTY,    40,	 EMPTY, EMPTY,	EMPTY,    70,	   36,    41,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T66
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T67
{EMPTY,    40,	 EMPTY, EMPTY,	EMPTY,    71,	   36,    41,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T68
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T69
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T70
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T71
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY,    75,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T72
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	   76}, //T73
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T74
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T75
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T76
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T77
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T78
{EMPTY,    40,	 EMPTY, EMPTY,	EMPTY,    81,	   36,    41,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T79
{EMPTY,    40,	 EMPTY, EMPTY,	EMPTY,    82,	   36,    41,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T80
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T81
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T82
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T83
{EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	 EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY, EMPTY,	EMPTY}, //T84
};

//char Reduce_temp 만들기 위해서 필요하다
char GOTO_Reduce[num_syntax_nonterminal + 10][100] = {
{'C','O','D','E',','},
{'V','D','E','C','L',','},
{'F','D','E','C','L',','},
{'A','R','G',','},
{'M','O','R','E','A','R','G','S',','},
{'B','L','O','C','K',','},
{'S','T','M','T',','},
{'A','S','S','I','G','N',','},
{'R','H','S',','},
{'E','X','P','R',','},
{'T','E','R','M',','},
{'F','A','C','T','O','R',','},
{'C','O','N','D',','},
{'R','E','T','U','R','N',','},
{'E','L','S','E',','}
};